sudo: required
dist: trusty

# install the pre-release chef-dk.  Use chef-stable-precise to install the stable release
addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

branches:
  only:
  - master

services: docker

env:
  matrix:
  - INSTANCE=keys-centos-7
  - INSTANCE=service-execute-multi-centos-5
  - INSTANCE=service-execute-multi-centos-6
  - INSTANCE=service-execute-multi-centos-7
  - INSTANCE=service-execute-multi-fedora-latest
  - INSTANCE=service-execute-multi-debian-8
  - INSTANCE=service-execute-multi-ubuntu-1404
  - INSTANCE=service-execute-multi-ubuntu-1604
  - INSTANCE=service-systemd-multi-centos-7
  - INSTANCE=service-systemd-multi-fedora-latest
  - INSTANCE=service-systemd-multi-debian-8
  - INSTANCE=service-systemd-multi-ubuntu-1604
#  - INSTANCE=service-upstart-multi-ubuntu-1404
  - INSTANCE=service-sysvinit-multi-centos-5
  - INSTANCE=service-sysvinit-multi-centos-6
  - INSTANCE=service-sysvinit-multi-ubuntu-1204

  fast_finish: true

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"

script:
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/cookstyle --version
  - /opt/chefdk/embedded/bin/cookstyle
  - /opt/chefdk/embedded/bin/foodcritic --version
  - /opt/chefdk/embedded/bin/foodcritic . --exclude spec -f any -P
  - /opt/chefdk/embedded/bin/rspec
  - KITCHEN_LOCAL_YAML=.kitchen.docker.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}
