rvm: 2.2

sudo: required

addons:
  apt:
    sources:
      - chef-current-precise
    packages:
      - chefdk

install: echo "skip bundle install"

services: docker

env:
  matrix:
  - INSTANCE=service-execute-multi-centos-5
  - INSTANCE=service-execute-multi-centos-6
  - INSTANCE=service-execute-multi-centos-7
  - INSTANCE=service-execute-multi-fedora-21
  - INSTANCE=service-execute-multi-debian-8
  - INSTANCE=service-execute-multi-ubuntu-1404
  - INSTANCE=service-execute-multi-ubuntu-1510
  - INSTANCE=service-systemd-multi-centos-7
  - INSTANCE=service-systemd-multi-fedora-21
  - INSTANCE=service-systemd-multi-debian-8
  - INSTANCE=service-systemd-multi-ubuntu-1510
  - INSTANCE=service-upstart-multi-ubuntu-1404
  - INSTANCE=service-sysvinit-multi-centos-5
  - INSTANCE=service-sysvinit-multi-centos-6
  - INSTANCE=service-sysvinit-multi-ubuntu-1204

before_script:
  - docker --version
  - docker info
  - mount
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/embedded/bin/chef gem install kitchen-dokken

script:
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/rubocop --version
  - /opt/chefdk/embedded/bin/rubocop
  - echo KITCHEN_YAML=.kitchen.yml kitchen verify ${INSTANCE}
  - KITCHEN_YAML=.kitchen.yml kitchen verify ${INSTANCE}

after_script:
  - docker images
  - docker ps -a
  - cat .kitchen/logs/kitchen.log
